### ISSUE TITLE
Incompatible with latest HDT 1.22.3

### ISSUE THREAD

**Issue by SullieLore** [ardittristan/HearthstoneQuestOverlay#16]
Great addon. Any chance of a fix? :)

Hearthstone Quest Overlay 1.5.8 is not compatible with HDT 1.22.3.
Make sure you are using the latest version of the Plugin and HDT.
System.MissingMethodException: Method not found: 'HearthMirror.ProcessView HearthMirror.Mirror.get_View()'.
at action, Boolean clearCache)
at HSReflection.Reflection.GetQuests()
at QuestOverlayPlugin.Util.QuestDataUtil.UpdateQuestData(Boolean force)
at QuestOverlayPlugin.Overlay.QuestListViewModel.Update(Boolean force)
at QuestOverlayPlugin.Plugin.ShowBattlegroundsQuests()
at QuestOverl ayPl ug i n.Overlay.QuestListButton. < On Mouse Enter> .MoveNext()
End of stack trace from previous location where exception was thrown
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.< state)
at System.Windows.Threading.ExceptionWrapper.lnternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper,TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ardittristan** [comment]
kind of fixed, but the new way HSDT does value reading is quite heavy on the cpu, so I still have to fix that (and images)
